apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-test
  template:
    metadata:
      labels:
        app: redis-test
    spec:
      containers:
      - name: redis
        image: redis:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 6379
